apiVersion: v1
kind: Service
metadata:
  name: {{ include "kube-stack.fullname" . }}-prometheus-service
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port:   '9090'
  labels:
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/created-by: kube-stack
    app.kubernetes.io/part-of: kube-stack
    control-plane: controller-manager
  {{- include "kube-stack.labels" . | nindent 4 }}
spec:
  selector:
    control-plane: controller-manager
  {{- include "kube-stack.selectorLabels" . | nindent 4 }}
  type: ClusterIP
  ports:
  - name: http
    port: 9090
    protocol: TCP
    targetPort: 9090
