# permissions for end users to edit podlimiters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: podlimiter-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kube-stack
    app.kubernetes.io/part-of: kube-stack
    app.kubernetes.io/managed-by: kustomize
  name: podlimiter-editor-role
rules:
- apiGroups:
  - podlimiter.kube-stack.me
  resources:
  - podlimiters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - podlimiter.kube-stack.me
  resources:
  - podlimiters/status
  verbs:
  - get
