---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - centralprobe.kube-stack.me
  resources:
  - centralprobes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - centralprobe.kube-stack.me
  resources:
  - centralprobes/finalizers
  verbs:
  - update
- apiGroups:
  - centralprobe.kube-stack.me
  resources:
  - centralprobes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods/finalizers
  verbs:
  - update
- apiGroups:
  - ""
  resources:
  - pods/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - podlimiter.kube-stack.me
  resources:
  - podlimiters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - podlimiter.kube-stack.me
  resources:
  - podlimiters/finalizers
  verbs:
  - update
- apiGroups:
  - podlimiter.kube-stack.me
  resources:
  - podlimiters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - podmarker.kube-stack.me
  resources:
  - podmarkers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - podmarker.kube-stack.me
  resources:
  - podmarkers/finalizers
  verbs:
  - update
- apiGroups:
  - podmarker.kube-stack.me
  resources:
  - podmarkers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - slo.kube-stack.me
  resources:
  - resourcestatetransitions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - slo.kube-stack.me
  resources:
  - resourcestatetransitions/finalizers
  verbs:
  - update
- apiGroups:
  - slo.kube-stack.me
  resources:
  - resourcestatetransitions/status
  verbs:
  - get
  - patch
  - update
