---
apiVersion: slo.kube-stack.me/v1beta1
kind: WatchSLO
metadata:
  labels:
    app.kubernetes.io/name: watchslo
    app.kubernetes.io/instance: watchslo-sample
    app.kubernetes.io/part-of: kube-stack
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kube-stack
  name: watchslo-config
spec:
  configs:
  - selector:
      apiVersion: v1
      kind: Pod
    targetResource: |
      apiVersion: v1
      kind: Pod
      metadata:
        name: kube-stack-target-pod
        namespace: kube-system
        labels:
          meta.k8s.alipay.com/zone: xxxxx
          sigma.ali/app-name: xxxx
          sigma.ali/instance-group: xxxxx
          sigma.ali/deploy-unit: xxxxx
          sigma.ali/site: xxxx
          meta.k8s.alipay.com/app-env: DEV
          app: nginx
      spec:
        containers:
        - name: main
          image: docker.io/xxxxxx/nginx:1.23.3
          resources:
            requests:
              cpu: 2
              memory: 2Gi
              ephemeral-storage: 3Gi
            limits:
              cpu: 2
              memory: 2Gi
              ephemeral-storage: 3Gi
  - selector:
      apiVersion: v1
      kind: Service
  - selector:
      apiVersion: v1
      kind: PersistentVolumeClaim
---
apiVersion: slo.kube-stack.me/v1beta1
kind: ResourceStateTransition
metadata:
  name: slo-pod-create
spec:
  selector:
    apiVersion: v1
    kind: Pod
  timer:
    eventName: timerEvent100s
    timerInSeconds: 600
  events:
  - name: Created
    requirements:
    - key: "metadata.creationTimestamp"
      operator: "notin"
      strValues:
      - ""
  - name: Ready
    requirements:
    - key: "status.conditions.#(type==Ready).status"
      operator: "in"
      strValues:
      - "True"
  transitions:
  - source:
    - BeginState
    event: Created
    target: CreatedState
    noMetric: true
  - source:
    - BeginState
    - CreatedState
    event: Ready
    target: SuccessState
  - source:
    - BeginState
    - CreatedState
    event: timerEvent100s
    target: FailState
---
apiVersion: slo.kube-stack.me/v1beta1
kind: ResourceStateTransition
metadata:
  name: resourcestatetransition-pod
spec:
  selector:
    apiVersion: v1
    kind: Pod
  events:
  - name: Created
    requirements:
    - key: "metadata.creationTimestamp"
      operator: "notin"
      strValues:
      - ""
  - name: Scheduled
    requirements:
    - key: "spec.nodeName"
      operator: "notin"
      strValues:
      - ""
  - name: Unschedulable
    requirements:
    - key: "status.conditions.#(type==PodScheduled).reason"
      operator: "in"
      strValues:
      - "Unschedulable"
  - name: IPAllocated
    requirements:
    - key: "status.podIP"
      operator: "notin"
      strValues:
      - ""
  - name: Ready
    requirements:
    - key: "status.conditions.#(type==Ready).status"
      operator: "in"
      strValues:
      - "True"
  - name: Delete
    requirements:
    - key: "metadata.deletionTimestamp"
      operator: "notin"
      strValues:
      - ""
  transitions:
  - source:
    - BeginState
    event: Created
    target: CreatedState
  - source:
    - CreatedState
    event: Scheduled
    target: ScheduledState
  - source:
    - CreatedState
    event: Unschedulable
    target: UnschedulableState
  - source:
    - ScheduledState
    event: IPAllocated
    target: IPAllocatedState
  - source:
    - IPAllocatedState
    event: Ready
    target: ReadyState
  - source:
    - "*"
    event: Delete
    target: DeleteState
---
apiVersion: slo.kube-stack.me/v1beta1
kind: ResourceStateTransition
metadata:
  name: resourcestatetransition-pvc
spec:
  selector:
    apiVersion: v1
    kind: PersistentVolumeClaim
  events:
  - name: Created
    requirements:
    - key: "metadata.creationTimestamp"
      operator: "notin"
      strValues:
      - ""
  - name: Bounded
    requirements:
    - key: "status.phase"
      operator: "in"
      strValues:
      - "Bound"
  - name: Delete
    requirements:
    - key: "metadata.deletionTimestamp"
      operator: "notin"
      strValues:
      - ""
  transitions:
  - source:
    - BeginState
    event: Created
    target: CreatedState
  - source:
    - CreatedState
    event: Bounded
    target: BoundedState
  - source:
    - "*"
    event: Delete
    target: DeleteState
