---
apiVersion: slo.kube-stack.me/v1beta1
kind: ResourceStateTransition
metadata:
  name: resourcestatetransition-pod
spec:
  selector:
    apiVersion: v1
    kind: Pod
  events:
  - name: Created
    requirements:
    - key: "metadata.creationTimestamp"
      operator: "notin"
      strValues:
      - ""
  - name: Scheduled
    requirements:
    - key: "spec.nodeName"
      operator: "notin"
      strValues:
      - ""
  - name: IPAllocated
    requirements:
    - key: "status.podIP"
      operator: "notin"
      strValues:
      - ""
  - name: Ready
    requirements:
    - key: "status.conditions.#(type==Ready).status"
      operator: "in"
      strValues:
      - "True"
  - name: Delete
    requirements:
    - key: "metadata.deletionTimestamp"
      operator: "notin"
      strValues:
      - ""
  - name: Deleted
    requirements:
    - key: "apiVersion"
      operator: "in"
      strValues:
      - ""
    - key: "kind"
      operator: "in"
      strValues:
      - ""
    - key: "metadata"
      operator: "in"
      strValues:
      - ""
    - key: "spec"
      operator: "in"
      strValues:
      - ""
  transitions:
  - source:
    - BeginState
    event: Created
    target: CreatedState
  - source:
    - CreatedState
    event: Scheduled
    target: ScheduledState
  - source:
    - ScheduledState
    event: IPAllocated
    target: IPAllocatedState
  - source:
    - IPAllocatedState
    event: Ready
    target: ReadyState
  - source:
    - "*"
    event: Delete
    target: DeleteState
  - source:
    - "*"
    event: Deleted
    target: DeletedState
    final: true
# ---
# apiVersion: slo.kube-stack.me/v1beta1
# kind: ResourceStateTransition
# metadata:
#   name: resourcestatetransition-pvc
# spec:
#   selector:
#     apiVersion: v1
#     kind: PersistentVolumeClaim
#   events:
#   - name: Created
#     requirements:
#     - key: "metadata.creationTimestamp"
#       operator: "notin"
#       strValues:
#       - ""
#   - name: Bounded
#     requirements:
#     - key: "status.phase"
#       operator: "in"
#       strValues:
#       - "Bound"
#   - name: Delete
#     requirements:
#     - key: "metadata.deletionTimestamp"
#       operator: "notin"
#       strValues:
#       - ""
#   - name: Deleted
#     requirements:
#     - key: "apiVersion"
#       operator: "in"
#       strValues:
#       - ""
#     - key: "kind"
#       operator: "in"
#       strValues:
#       - ""
#     - key: "metadata"
#       operator: "in"
#       strValues:
#       - ""
#     - key: "spec"
#       operator: "in"
#       strValues:
#       - ""
#   transitions:
#   - source:
#     - BeginState
#     event: Created
#     target: CreatedState
#   - source:
#     - CreatedState
#     event: Bounded
#     target: BoundedState
#   - source:
#     - "*"
#     event: Delete
#     target: DeleteState
#   - source:
#     - DeleteState
#     event: Deleted
#     target: DeletedState
#     final: true
