apiVersion: slo.kube-stack.me/v1beta1
kind: ResourceStateTransition
metadata:
  name: resourcestatetransition-sample
spec:
  selector:
    apiVersion: v1
    kind: Pod
  states:
  - name: BeginState
  - name: CreatedState
  - name: ScheduledState
  - name: ReadyState
  # orders matters
  events:
  - name: CreateEvent
    matches:
    - selector:
        apiVersion: v1
        kind: pod
      # 支持gjon表达式
      labelSelector: |
        metadata.creationTimestamp!=""
  - name: ScheduleEvent
    matches:
    - selector:
        apiVersion: v1
        kind: pod
      fieldSelector: "spec.nodeName!="
    - selector:
        apiVersion: v1
        kind: Event
      labelSelector: |
        message="Synced successfully", reason="Synced"
  transitions:
  - source:
    - BeginState
    target: CreatedState
    event: CreateEvent
  - source:
    - CreatedState
    target: ScheduledState
    event: ScheduleEvent
